### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/ASkyBlock-Nukkit#10]
17:42:56 [WARNING] NycuRO moved too fast, reverting movement
17:43:08 [INFO] [SkyBlock] An error occured while fecthing SQLite: #id 0
17:43:08 [INFO] [SkyBlock] An error occured while fecthing SQLite: #location #X100#Z100
17:43:08 [INFO] [SkyBlock] An error occured while saving SQLite: #id 1#Text 1 Cause of: 1AND null

Not work if i'm used : "/is" . Help @larryTheCoder ?

**Comment by NycuRO** [comment]
And if i'm using :"/is create" :   

17:44:15 [CRITICAL] Unhandled exception executing command 'is create' in is: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.larryTheCoder.command.island.CreateISubCommand.execute(CreateISubCommand.java:70)
        at com.larryTheCoder.Commands.execute(Commands.java:111)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:244)
        at cn.nukkit.Server.dispatchCommand(Server.java:635)
        at cn.nukkit.Player.handleDataPacket(Player.java:2956)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1910)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:156)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:988)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:64)

17:44:15 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 1
        at com.larryTheCoder.command.island.CreateISubCommand.execute(CreateISubCommand.java:70)
        at com.larryTheCoder.Commands.execute(Commands.java:111)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:244)
        at cn.nukkit.Server.dispatchCommand(Server.java:635)
        at cn.nukkit.Player.handleDataPacket(Player.java:2956)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1910)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:156)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:65)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:988)
        at cn.nukkit.Server.tickProcessor(Server.java:791)
        at cn.nukkit.Server.start(Server.java:770)
        at cn.nukkit.Server.<init>(Server.java:455)
        at cn.nukkit.Nukkit.main(Nukkit.java:64)

**Comment by larryTheCoder** [comment]
Added to todo list

You can use `/is` instead of `/is create`

**Comment by NycuRO** [comment]
@larryTheCoder Not todo man.

If i'm used /is , get this error!

**Comment by NycuRO** [comment]
@larryTheCoder larry?

Isn't NOT todo. Is one bug /error. You can fix?

**Comment by NycuRO** [comment]
@larryTheCoder Update please, fix problem?

**Comment by NycuRO** [comment]
Fixed
