### ISSUE TITLE
Other issue

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/ASkyBlock-Nukkit#11]
12:46:45 [CRITICAL] Unhandled exception executing command 'c' in challenges: java.lang.ArrayIndexOutOfBoundsException: 0
        at com.larryTheCoder.command.ChallangesCMD.execute(ChallangesCMD.java:71)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:646)
        at cn.nukkit.Player.handleDataPacket(Player.java:2947)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1906)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:999)
        at cn.nukkit.Server.tickProcessor(Server.java:802)
        at cn.nukkit.Server.start(Server.java:781)
        at cn.nukkit.Server.<init>(Server.java:466)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

12:46:45 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 0
        at com.larryTheCoder.command.ChallangesCMD.execute(ChallangesCMD.java:71)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:225)
        at cn.nukkit.Server.dispatchCommand(Server.java:646)
        at cn.nukkit.Player.handleDataPacket(Player.java:2947)
        at cn.nukkit.network.Network.processPackets(Network.java:185)
        at cn.nukkit.network.Network.processBatch(Network.java:156)
        at cn.nukkit.Player.handleDataPacket(Player.java:1906)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:155)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:999)
        at cn.nukkit.Server.tickProcessor(Server.java:802)
        at cn.nukkit.Server.start(Server.java:781)
        at cn.nukkit.Server.<init>(Server.java:466)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

@larryTheCoder

**Comment by larryTheCoder** [comment]
Command is not ready yet `| Not Implemented |`

**Comment by larryTheCoder** [comment]
Okay its done @NycuRO Some value fix and some mistakes with my database
