### ISSUE TITLE
Database Bug

### ISSUE THREAD

**Issue by PikyCZ** [larryTheCoder/ASkyBlock-Nukkit#15]
Enabling ASkyBlock v0.3.0
19:54:21 [INFO] [ASkyBlock] Seccessfully checked config.yml
19:54:21 [INFO] [ASkyBlock] Loading source ASkyBlock v0.3.0
19:54:21 [INFO] ------------------------------------------------------------
19:54:21 [INFO] [ASkyBlock] Loading offline messages...
19:54:21 [INFO] [ASkyBlock] Loading the Island Framework
19:54:21 [INFO] <SMC> Schematic Post:
19:54:21 [INFO]  - ISLAND Info:
19:54:21 [INFO]    - Blocks: 138
19:54:21 [INFO]    - SafeSpot: 0 SafeSpot found
19:54:21 [INFO]  - NETHER Info:
19:54:21 [INFO]    - Blocks: 7678
19:54:21 [INFO]    - SafeSpot: 0 SafeSpot found
19:54:21 [INFO]  - DOUBLE Info:
19:54:21 [INFO]    - Blocks: 595
19:54:21 [INFO]    - SafeSpot: 0 SafeSpot found
19:54:21 [INFO]  - HARDER Info:
19:54:21 [INFO]    - Blocks: 113
19:54:21 [INFO]    - SafeSpot: 0 SafeSpot found
19:54:21 [INFO] <SMC> Seccessfully loaded island Schematic
19:54:21 [INFO] Preparing level "SkyBlock"
19:54:21 [ALERT] java.lang.RuntimeException: java.lang.AbstractMethodError: Method org/sqlite/RS.isClosed()Z is abstract
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:614)
        at cn.nukkit.Server.enablePlugins(Server.java:603)
        at cn.nukkit.Server.<init>(Server.java:456)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.AbstractMethodError: Method org/sqlite/RS.isClosed()Z is abstract
        at org.sqlite.RS.isClosed(RS.java)
        at com.larryTheCoder.database.ASConnection.getWorlds(ASConnection.java:317)
        at com.larryTheCoder.ASkyBlock.generateLevel(ASkyBlock.java:459)
        at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:368)
        at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:297)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:119)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        ... 4 more

19:54:21 [INFO] Disabling ASkyBlock v0.3.0
19:54:21 [INFO] [ASkyBlock] Saving islands framework

Server disable plugin and server freeze

**Comment by larryTheCoder** [comment]
It seems like the problem starts from sqlite class. Try to change DbLib plugin on my source `lib/DbLib.jar`

**Comment by PikyCZ** [comment]
ok

**Comment by PikyCZ** [comment]
Nope this notworking 

_Sent from my Asus ASUS_X00AD using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by larryTheCoder** [comment]
I will try to find out what it cause 
PS: i dont get this error

**Comment by larryTheCoder** [comment]
Before i made other changes, You still getting this error?
