### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by victorpk1999** [larryTheCoder/ASkyBlock-Nukkit#17]
11:51:45 [ALERT] java.lang.RuntimeException: java.lang.IllegalAccessError: class
 org.sqlite.SQLiteConfig$TransactionMode cannot access its superinterface org.sq
lite.SQLiteConfig$PragmaValue
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
        at cn.nukkit.Server.enablePlugin(Server.java:620)
        at cn.nukkit.Server.enablePlugins(Server.java:609)
        at cn.nukkit.Server.<init>(Server.java:462)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.IllegalAccessError: class org.sqlite.SQLiteConfig$Transacti
onMode cannot access its superinterface org.sqlite.SQLiteConfig$PragmaValue
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:4
4)
        at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.jav
a:141)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:4
0)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:2
8)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.sqlite.core.CoreConnection.<clinit>(CoreConnection.java:46)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.larryTheCoder.database.variables.SQLiteDatabase.openConnection(SQ
LiteDatabase.java:55)
        at com.larryTheCoder.database.ASConnection.<init>(ASConnection.java:50)
        at com.larryTheCoder.ASkyBlock.registerObject(ASkyBlock.java:361)
        at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:297)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:
113)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
        ... 4 more

11:51:45 [INFO] Disabling ASkyBlock v0.3.0
11:51:45 [INFO] [ASkyBlock] Saving islands framework
11:51:45 [ALERT] java.lang.NullPointerException
        at com.larryTheCoder.ASkyBlock.saveLevel(ASkyBlock.java:335)
        at com.larryTheCoder.ASkyBlock.onDisable(ASkyBlock.java:308)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91)
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java
:128)
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:520)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:452)
        at cn.nukkit.Server.enablePlugin(Server.java:620)
        at cn.nukkit.Server.enablePlugins(Server.java:609)
        at cn.nukkit.Server.<init>(Server.java:462)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by larryTheCoder** [comment]
@victorpk1999 recheck your Database version or vendor version. This will considered as solved
