### ISSUE TITLE
Not work with latest nukkit

### ISSUE THREAD

**Issue by NycuRO** [larryTheCoder/ASkyBlock-Nukkit#19]
18:59:23 [CRITICAL] Unhandled exception executing command 'skyblock' in is: java.lang.ArrayIndexOutOfBoundsException: 12
        at cn.nukkit.block.BlockVine.onUpdate(BlockVine.java:178)
        at cn.nukkit.level.Level.updateAround(Level.java:1258)
        at cn.nukkit.level.Level.setBlock(Level.java:1689)
        at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:435)
        at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:485)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:484)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:229)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:188)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:63)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:52)
        at com.larryTheCoder.Commands.execute(Commands.java:91)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:638)
        at cn.nukkit.Player.handleDataPacket(Player.java:3127)
        at cn.nukkit.network.Network.processPackets(Network.java:180)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1992)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

18:59:23 [ALERT] java.lang.ArrayIndexOutOfBoundsException: 12
        at cn.nukkit.block.BlockVine.onUpdate(BlockVine.java:178)
        at cn.nukkit.level.Level.updateAround(Level.java:1258)
        at cn.nukkit.level.Level.setBlock(Level.java:1689)
        at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:435)
        at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:485)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:484)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:229)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:188)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:63)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:52)
        at com.larryTheCoder.Commands.execute(Commands.java:91)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:638)
        at cn.nukkit.Player.handleDataPacket(Player.java:3127)
        at cn.nukkit.network.Network.processPackets(Network.java:180)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1992)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:996)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by larryTheCoder** [comment]
Cannot reproduce... Maybe you do:

1.   Put one Minecart Hopper to rail
2.   Click to them
3.   Get error

But.. It not making sense that minecarts making this bug... The main bug is vine 😕

**Comment by NycuRO** [comment]
@larryTheCoder Not this..lol...

Use latest version for nukkit and use /skyblock

**Comment by larryTheCoder** [comment]
Question: Did you use original schematic or default schematic
If you say:

**YES**: 
The problem might be the false metadata from PC Blocks 
And yes quite a bit that Minecraft PE not support this operation yet
**NO**:
 Skip my question go on WIP

**Comment by NycuRO** [comment]
When i put command: "/is", get this error: @larryTheCoder 

**DEBUG LVL 3**

17:00:17 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
        at cn.nukkit.level.Level.setChunk(Level.java:2376)
        at cn.nukkit.level.Level.generateChunkCallback(Level.java:2321)
        at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:164)
        at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
        at cn.nukkit.Server.tick(Server.java:1004)
        at cn.nukkit.Server.tickProcessor(Server.java:794)
        at cn.nukkit.Server.start(Server.java:773)
        at cn.nukkit.Server.<init>(Server.java:464)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

17:00:19 [DEBUG] Level "world" took 75.0ms, setting tick rate to 2 ticks
17:00:19 [DEBUG] Raising level "world" tick rate to 1 ticks


**WHEN I SET /IS DELETE**

![image](https://user-images.githubusercontent.com/13573011/28877204-4f83816a-77a4-11e7-8645-fd1aaea3091e.png)

**WHEN I'M TELEPORTED SKY IS LIKE IN NETHER AND I GET DOWN FROM ISLAND**

![image](https://user-images.githubusercontent.com/13573011/28877224-664ab044-77a4-11e7-93e2-92458b4127ff.png)


**FIX FOR GET DOWN FROM ISLAND **

When i'm teleported, i'm get down, but I DON'T DIE. I get down.

For fix need add coord spawn to WHERE IS OBSIDIAN NOT WHERE IS COBBLESTONE.

![image](https://user-images.githubusercontent.com/13573011/28877290-99854460-77a4-11e7-94a4-1243692e99bd.png)

**Comment by NycuRO** [comment]
**Other bug**

**Chest is invisible**

![image](https://user-images.githubusercontent.com/13573011/28877454-1493f1c4-77a5-11e7-8122-8dee421e976d.png)

**When i broken, don't have items**

![image](https://user-images.githubusercontent.com/13573011/28877479-214d5ff4-77a5-11e7-8758-654100ab2b86.png)

**Comment by larryTheCoder** [comment]
Okay....

**Comment by NycuRO** [comment]
@larryTheCoder 👍 

Good job bro <3

**Comment by NycuRO** [comment]
**I'm used default settings, latest version plugin with latest version nukkit and Economy and DbLib from /lib"

Version Nukkit: https://github.com/Nukkit/Nukkit/commit/b190802a4a3f67064ceae824dbddae16d4974fb5

Version ASkyBlock: https://github.com/larryTheCoder/ASkyBlock-Nukkit/commit/fe0713ae8aa06363346b2c0ba00adc9b3fe3ad20

**Comment by larryTheCoder** [comment]
Wait... Sky is like a NeTher??? Impossible

**Comment by NycuRO** [comment]
@larryTheCoder Watch photo lmao

**Comment by larryTheCoder** [comment]
A lot of changes has been made since v1.1.3. I am afraid that new version of nukkit has new API changes and complex API access. BUT it not my excuse to stop contribute this plugin. Only I can do is trying to fix or waiting.

**Comment by NycuRO** [comment]
@larryTheCoder Ok bro 👍

**Comment by NycuRO** [comment]
@larryTheCoder 
Console get this, but i don't know why.

17:14:05 [INFO] Usage: /title <clear|reset> OR /title <title|subtitle|actionbar> <title text> OR /title 
17:14:05 [INFO] Usage: /title <clear|reset> OR /title <title|subtitle|actionbar> <title text> OR /title 

I don't know how reproduce..

**Comment by larryTheCoder** [comment]
My wrong xD. I noticed that. Wrong parameters

**Comment by NycuRO** [comment]
@larryTheCoder You have discord?

**Comment by larryTheCoder** [comment]
The `/island delete` command is works (Maybe 75%... Need tests)

**Comment by NycuRO** [comment]
@larryTheCoder Good. I test now.

**Comment by larryTheCoder** [comment]
@NycuRO could you star this repository :D Its could help  👍

**Comment by NycuRO** [comment]
@larryTheCoder It's already.

**Comment by NycuRO** [comment]
@larryTheCoder You fixed all bugs? 👍

**Comment by larryTheCoder** [comment]
@NycuRO Fixed but not tested

**Comment by NycuRO** [comment]
@larryTheCoder Have you discord?

**Comment by larryTheCoder** [comment]
@NycuRO no i don't have

**Comment by NycuRO** [comment]
@larryTheCoder Facebook, anything where can i contact you?

**Comment by larryTheCoder** [comment]
@NycuRO still new but can be [dont click me](https://www.facebook.com/adam.matthew.1232)

**Comment by NycuRO** [comment]
@larryTheCoder Can you give me your discord?

**Comment by larryTheCoder** [comment]
@NycuRO larryTheCoder#0060
- Is this right? I still new :3

**Comment by NycuRO** [comment]
@larryTheCoder Yes.
