### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#21]
![image](https://user-images.githubusercontent.com/26197131/28926121-8f3ddf50-786f-11e7-987a-5b133c5db457.JPG)

17:14:05 [INFO] Usage: /title <player> <clear|reset> OR /title <player> <title|subtitle|actionbar> <title text> OR /title <player> <times> <fade in time> <stay time> <fade out time>
17:14:05 [INFO] Usage: /title <player> <clear|reset> OR /title <player> <title|subtitle|actionbar> <title text> OR /title <player> <times> <fade in time> <stay time> <fade out time>
17:14:05 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at cn.nukkit.level.Level.setChunk(Level.java:2376)
	at cn.nukkit.level.Level.generateChunkCallback(Level.java:2321)
	at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:164)
	at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
	at cn.nukkit.Server.tick(Server.java:1004)
	at cn.nukkit.Server.tickProcessor(Server.java:794)
	at cn.nukkit.Server.start(Server.java:773)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by PetteriM1** [comment]
And chest is invisible.

**Comment by NycuRO** [comment]
@PetteriM1 Same.
