### ISSUE TITLE
Chest

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#23]
Good job! But chest is still invisible.

Edit: When i go back to spawn and come back again CHEST IS VISIBLE, BUT EMPTY.

**Comment by larryTheCoder** [comment]
Comfirmed

**Comment by larryTheCoder** [comment]
commit aeb63650d6afbcb86d5bba911005f36575ce9f37 might fix the problem

**Comment by PetteriM1** [comment]
good job but chest is still invisible

**Comment by PetteriM1** [comment]
When creating island:

11:05:08 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at cn.nukkit.level.Level.setChunk(Level.java:2376)
	at cn.nukkit.level.Level.generateChunkCallback(Level.java:2321)
	at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:164)
	at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
	at cn.nukkit.Server.tick(Server.java:1004)
	at cn.nukkit.Server.tickProcessor(Server.java:794)
	at cn.nukkit.Server.start(Server.java:773)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

11:05:08 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at cn.nukkit.level.Level.setChunk(Level.java:2376)
	at cn.nukkit.level.Level.generateChunkCallback(Level.java:2321)
	at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:164)
	at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
	at cn.nukkit.Server.tick(Server.java:1004)
	at cn.nukkit.Server.tickProcessor(Server.java:794)
	at cn.nukkit.Server.start(Server.java:773)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

11:05:08 [CRITICAL] Exception while async task 0 invoking onCompletion
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1466)
	at cn.nukkit.level.Level.setChunk(Level.java:2376)
	at cn.nukkit.level.Level.generateChunkCallback(Level.java:2321)
	at cn.nukkit.level.generator.task.PopulationTask.onCompletion(PopulationTask.java:164)
	at cn.nukkit.scheduler.AsyncTask.collectTask(AsyncTask.java:83)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:301)
	at cn.nukkit.Server.tick(Server.java:1004)
	at cn.nukkit.Server.tickProcessor(Server.java:794)
	at cn.nukkit.Server.start(Server.java:773)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by larryTheCoder** [comment]
@PetteriM1 did you delete the island world before attempting `/is` command? I had tested this and it works fine

**Comment by larryTheCoder** [comment]
Comfirmed. xD

**Comment by larryTheCoder** [comment]
Okay, I dont know why this happening... Nukkit bug I guess.
Load in SkyBlock world: Okay
Load outside SkyBlock world: Not Okay

**Comment by PetteriM1** [comment]
Chest is still empty.

**Comment by larryTheCoder** [comment]
Okay it works. close
