### ISSUE TITLE
Cannot reload if players online

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#24]
### Issue Description
If you reload server when there is players online, ASkyBlock disabled.

### Steps to Reproduce the Issue
1. Go to your server where is ASkyBlock installed.
2. Reload server.
3. Look to console.

### OS and Versions
* Nukkit Version: 1.1.3
* Java Version: 1.8_131
* ASkyBlock version: Build #62

### Crashdump, Backtrace or Other Files

11:13:43 [INFO] Enabling ASkyBlock v0.3.1
11:13:43 [INFO] [ASkyBlock] Seccessfully checked config.yml
11:13:43 [INFO] [ASkyBlock] Loading source ASkyBlock v0.3.1
11:13:43 [INFO] ------------------------------------------------------------
11:13:43 [ALERT] java.lang.RuntimeException: java.lang.NullPointerException
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
	at cn.nukkit.Server.enablePlugin(Server.java:620)
	at cn.nukkit.Server.enablePlugins(Server.java:609)
	at cn.nukkit.Server.reload(Server.java:685)
	at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
	at cn.nukkit.Server.dispatchCommand(Server.java:638)
	at cn.nukkit.command.CommandReader.lambda$run$0(CommandReader.java:75)
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
	at cn.nukkit.Server.tick(Server.java:1004)
	at cn.nukkit.Server.tickProcessor(Server.java:794)
	at cn.nukkit.Server.start(Server.java:773)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NullPointerException
	at com.larryTheCoder.ASkyBlock.getPlayerInfo(ASkyBlock.java:167)
	at com.larryTheCoder.ASkyBlock.getIslandLevel(ASkyBlock.java:141)
	at com.larryTheCoder.listener.chat.ChatHandler.<init>(ChatHandler.java:48)
	at com.larryTheCoder.ASkyBlock.initIslands(ASkyBlock.java:323)
	at com.larryTheCoder.ASkyBlock.onEnable(ASkyBlock.java:300)
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
	... 14 more

11:13:43 [INFO] Disabling ASkyBlock v0.3.1
11:13:43 [INFO] [ASkyBlock] Saving islands framework
11:13:43 [ALERT] java.lang.NullPointerException
	at com.larryTheCoder.ASkyBlock.saveLevel(ASkyBlock.java:339)
	at com.larryTheCoder.ASkyBlock.onDisable(ASkyBlock.java:312)
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91)
	at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:128)
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:520)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:452)
	at cn.nukkit.Server.enablePlugin(Server.java:620)
	at cn.nukkit.Server.enablePlugins(Server.java:609)
	at cn.nukkit.Server.reload(Server.java:685)
	at cn.nukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:28)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
	at cn.nukkit.Server.dispatchCommand(Server.java:638)
	at cn.nukkit.command.CommandReader.lambda$run$0(CommandReader.java:75)
	at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
	at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
	at cn.nukkit.Server.tick(Server.java:1004)
	at cn.nukkit.Server.tickProcessor(Server.java:794)
	at cn.nukkit.Server.start(Server.java:773)
	at cn.nukkit.Server.<init>(Server.java:464)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by larryTheCoder** [comment]
Comfirmed and fixed
