### ISSUE TITLE
Island Guard

### ISSUE THREAD

**Issue by PetteriM1** [larryTheCoder/ASkyBlock-Nukkit#30]
Server spams this in console, plugin still works:

[CRITICAL] Could not pass event 'cn.nukkit.event.block.BlockIgniteEvent' to 'ASkyBlock v0.3.7-BETA': null on com.larryTheCoder.listener.IslandGuard
[ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.entity.weather.EntityLightning.onUpdate(EntityLightning.java:141)
	at cn.nukkit.level.Level.doTick(Level.java:817)
	at cn.nukkit.Server.checkTickUpdates(Server.java:935)
	at cn.nukkit.Server.tick(Server.java:1010)
	at cn.nukkit.Server.tickProcessor(Server.java:811)
	at cn.nukkit.Server.start(Server.java:790)
	at cn.nukkit.Server.<init>(Server.java:468)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
Caused by: java.lang.NullPointerException
	at com.larryTheCoder.listener.IslandGuard.actionAllowed(IslandGuard.java:150)
	at com.larryTheCoder.listener.IslandGuard.onBlockIgnite(IslandGuard.java:1291)
	at sun.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 10 more

**Comment by larryTheCoder** [comment]
@PetteriM1 I get this error. You can ignore that message and others (As this plugin is still in development).
By the way in case that (you dont know that I know these bugs are):
- This issue
- plugin cannot restart while Player inside (Fixed)
- Delete island wont work
- Challenge, teamchat, asc commands dont work
- Other listeners problem (other than: breaking, interact, place)

But thanks for creating an issue for this repository (Felling alone when i was building this by my own 😢 )
Wait for others future release :+1:

**Comment by zahfro** [comment]
where do i go to download the ASkyblock plugin
