### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by iDirtniverse** [larryTheCoder/ASkyBlock-Nukkit#6]
http://pastebin.com/jAEZhxgK

**Comment by larryTheCoder** [comment]
Do you have DbLib plugin installed?

**Comment by iDirtniverse** [comment]
Oh it's required? My bad, sorry I will install it now and we'll see :)

**Comment by iDirtniverse** [comment]
Alright problem solved but I have one request, is it generator fault for generating 1 layer on water?

**Comment by larryTheCoder** [comment]
no its not the generator problem, you can configure the config `seaLevel` for that.

**Comment by Datblockcom** [comment]
I'm getting a problem with the generator. No island and also generates normal world with the SeaLevel at bottom.

On /is
`03:46:14 [INFO] [SkyBlock]BIOME: PLAINS
03:46:14 [INFO] [SkyBlock]Location: x: 100 y: 60 z: 100 levelname: SkyBlock
03:46:14 [INFO] [SkyBlock]IslandName: JackSlacks
03:46:14 [INFO] [SkyBlock]SPOT: 178
> Exception in thread "Nukkit Asynchronous Task Handler #6" java.lang.NullPointerException
        at larryTheCoder.SafeSpotTeleport$1.onRun(SafeSpotTeleport.java:145)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

        at larryTheCoder.SafeSpotTeleport$1.onRun(SafeSpotTeleport.java:145)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
03:46:49 [INFO] [SkyBlock]SPOT: 178
> 
        at larryTheCoder.SafeSpotTeleport$1.onRun(SafeSpotTeleport.java:145)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

**Comment by larryTheCoder** [comment]
that is the problem. i get i tried to fix with `plugin.getSchematic("default").pasteWESchematic(locIsland, p, true)` but no blocks were generated. maybe WorldEdit error?

**Comment by Datblockcom** [comment]
Is there a way to fix it?
